name: skeleton_morph
description: Crea skeletons automáticos desde tu UI real, con hints opcionales para obtener resultados precisos en cards, imágenes, textos y listas.
version: 0.1.1
repository: https://github.com/JhonatanAlvarezDhoz/skeleton_morph
issue_tracker: https://github.com/JhonatanAlvarezDhoz/skeleton_morph/issues

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
